environment:
  name: "marl_cybersecurity"
  episode_length: 100
  state_dim: 4
  agents:
    - "detection"
    - "response"
    - "attacker"

rewards:
  detection:
    correct: 1.0
    false_positive: -2.0
    missed_attack: -5.0
  response:
    correct_block: 5.0
    wrong_block: -10.0
    allow_attack: -3.0
  attacker:
    default: 0.0

state_bounds:
  flows_per_sec: [0, 1000]
  avg_pkt_size: [0, 1500]
  failed_logins: [0, 100]
  entropy: [0, 8]

attack_params:
  scan:
    flows_multiplier: 3.0
    entropy_increase: 1.5
  ddos:
    flows_multiplier: 10.0
    avg_pkt_decrease: 0.5
  bruteforce:
    failed_logins_increase: 20.0
    entropy_decrease: 0.7

baseline_state:
  flows_per_sec: 50.0
  avg_pkt_size: 600.0
  failed_logins: 2.0
  entropy: 5.0

noise:
  std: 0.05